apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nktomer45/frontend:latest
          env:
            - name: VITE_API_URL
              value: http://backend-service:5000
          ports:
            - containerPort: 80
